### ISSUE TITLE
great. only one thing left. Do you want to hand in now? we need to assign a group on Ilias.

### ISSUE THREAD

**Issue by bishutsuka** [bishutsuka/model-checking-project#5]

**Comment by bishutsuka** [comment]
Sure. Please assign me to your group

**Comment by yingwang1728** [comment]
Do I make it correct?

**Comment by yingwang1728** [comment]
I have added you in the team. But I am not sure whether it works or not? Can you see that? Is that work?
![屏幕快照 2017-12-19 17.59.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2fe8ade4306300136f3389/125516c66e82c728ace21e0d466d4575a65b762c502238a6631da2c478116a227b49f27230d4b466ea1b35545d4d52be011a001ea9aacd39aca43921880a5ee88568597c953f42adb8821dba08ef27da48d6a4a0980e91b6697abad2c51a7c0c0f0a88f65734a59848cf58f548e54f5dac15242e.png)

**Comment by yingwang1728** [comment]
I have uploaded it
![屏幕快照 2017-12-19 18.30.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a2fe8ade4306300136f3389/125516c66e82c728ace21e0d466d4575a65b762c502238a6631da2c478116a227b49f27230d4bb66ec1235555c4d52be011a001ea9aacd39aca43921880a5ee88568597c953f42adb8821dba08ef27da48d6a4a0980e91b6697abad2c51a7c0c0f0a88f85734a59848cf58f24de94b54a115242e.png)
